### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by EvilSeal1980** [SLywnow/hi-themes-refind#1]
How did you made that icons with that design??
Can you make and share the icon for me with that design
Actually I use Garuda Linux and can't find that type of icon
I am sharing the icon, please make the logo design with red accent if possible
![avatar-nico.png](https://user-images.githubusercontent.com/73596802/103484972-e601ee80-4e18-11eb-95fd-645492f330ab.png)

**Comment by SLywnow** [comment]
I just found the standard system icons on the Internet and edited them a little in photoshop

**Comment by SLywnow** [comment]
But i like your idea
